### ISSUE TITLE
Setup proper logging for Timeline Tracker API

### ISSUE THREAD

**Issue by kirypto** [kirypto/TimelineTracker#80]
- [ ] Configure logging in the application boot-up
- [ ] Add a configuration setting for a log file location _(default to application root?)_
- [ ] Audit the codebase for `print(...)` statements that should be log statements and convert them
